# Generated by Django 4.0.6 on 2022-09-11 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0003_remove_payment_api_payment_type'),
    ]

    operations = [
    ]
