# Generated by Django 4.1.13 on 2026-03-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_user_login_status'),
        ('doctor', '0045_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='appointed_hospitals',
            field=models.ManyToManyField(blank=True, related_name='appointed_doctors', to='hospital.hospital_information'),
        ),
    ]
