# Generated by Django 4.1.13 on 2026-03-22 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0046_doctor_information_appointed_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_test',
            name='assigned_lab_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='report_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='test_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
