# Generated by Django 4.1.13 on 2026-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_prescription_test_assigned_lab_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
